[workspace]
resolver = "3"
members = [
    # Bounded contexts
    # Scaffolding
    "crates/scaffolding/domain",
    "crates/scaffolding/application",
    "crates/scaffolding/infrastructure",

    # Workspace
    "crates/workspace/domain",
    "crates/workspace/application",
    "crates/workspace/infrastructure",

    # Config
    "crates/config/domain",
    "crates/config/application",
    "crates/config/infrastructure",

    # Shared
    "crates/shared/domain",
    "crates/shared/infrastructure",

    # CLI
    "cli",

    # Binaries
    # main
    "bin"
]

[workspace.dependencies]
toml_edit = "0.25"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3