[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
scaffolding_application = { path = "../crates/scaffolding/application" }
scaffolding_domain = { path = "../crates/scaffolding/domain" }
scaffolding_infrastructure = { path = "../crates/scaffolding/infrastructure" }
workspace_application = { path = "../crates/workspace/application" }
workspace_infrastructure = { path = "../crates/workspace/infrastructure" }
